// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/Stock/Content.vue')['default']
    Header: typeof import('./src/components/Stock/Header.vue')['default']
    Storefront: typeof import('./src/components/Stock/Storefront.vue')['default']
  }
}

export { }
